version: "3"

volumes: 
    shareddata:

### Join existing network "env_rede"
# networks:
  # default:
    # external:
      # name: env_rede
      
### Create a new network      
networks:
  mynetwork1:

services:

  alpine:
    image: "alpine:latest"    
    container_name: alpine
    command: tail -F anything
    #ports:
    #  - "80:80"    
    hostname: alpine    
    environment:
      - VAR1=var1
    networks:
      - mynetwork1
      
  busybox:
    image: "busybox"
    container_name: busybox    
    volumes:
      - shareddata:/data
    command: tail -F anything
    #ports:
    #  - "80:80"    
    hostname: busybox    
    environment:
      - VAR1=var1
    networks:
      - mynetwork1
      
  fakegcloudserver:
    image: "fsouza/fake-gcs-server"
    container_name: fakegcloudserver    
    volumes:
      - ./FunctionalTests/TestBuckets:/data
    #command: tail -F anything
    ports:
     - "4443:4443"    
    hostname: fakegcloudserver    
    environment:
      - VAR1=var1
    networks:
      - mynetwork1     
      
           
  # dotnetsdk:
    # image: "mcr.microsoft.com/dotnet/core/sdk:2.2"
    # container_name: dotnetsdk
    # #command: pwsh -Command Test-Connection -TargetName fakegcloudserver -IPv4 -Count 3 -Delay 3
    # stdin_open: true    
    # hostname: dotnetsdk    
    # environment:
      # - VAR1=var1
    # networks:
      # - mynetwork1
   
  powershell:
    image: "mcr.microsoft.com/powershell:latest"
    container_name: powershell
    command: pwsh -Command Test-Connection -TargetName fakegcloudserver -IPv4 -Count 3 -Delay 3
    stdin_open: true    
    hostname: powershell    
    environment:
      - VAR1=var1
    networks:
      - mynetwork1
    depends_on:
      - fakegcloudserver
    
    